### ISSUE TITLE
Confusion over FEP protocol

### ISSUE THREAD

**Issue by DreamCykl** [OpenBioSim/biosimspace#100]
Hello,

I have been reading through the documentation for [BSS.FreeEnergy](https://biosimspace.openbiosim.org/api/index_FreeEnergy.html) and am feeling a little confused by the description of the module, specifically by the reference to PMF computation. Perhaps I have misunderstood, but my belief is that PMF is when geometric reaction coordinates are provided and a 'pulling' simulation is used to remove the ligand from the binding site. This differs from conventional FEP, where a series of alchemical states (between lambda 0 and 1) are simulated and estimators are used to extract the energy associated between transition from 0-1.  

Would it be possible to clarify how the FEP protocol in BSS works, and perhaps provide some pointers to further documentation/tutorials if they are available?

Thank you

**Comment by jmichel80** [comment]
PMF is general concept that is not limited to physical reaction coordinates. 
you could check https://github.com/michellab/BioSimSpaceTutorials and   https://github.com/michellab/bssccpbiosim2022  for some examples of FEP calculations with BSS
