### ISSUE TITLE
Issue reading in PDB/top file

### ISSUE THREAD

**Issue by noahharrison64** [OpenBioSim/biosimspace#127]
Hi all,

I've been having a strange issue reading in a PDB/top files using BSS, however it's not entirely clear to me that this is an issue with BSS or my setup. The reason I say this is that I've had no issue with these files on one of my work stations, however have been encountering the issue on a cloud server. What's strange is both the work station and the server use the same version of BSS (2023.1.2) and Sire (2023.1.4). I have also tried using the latest version of BSS on the web server and have encountered the same issue.

Simply, I'm trying to read in the molecule using  
`BSS.IO.readMolecules(['protein_pdb2gmx.pdb', 'topol.top'])`

On my work station this isn't a problem and returns 
`<BioSimSpace.System: nMolecules=1>`

However on the server I receive the following error. 

```
OSError: SireError::io_error: Cannot load the molecules: There is not enough information in this parser (PDB2( 
nMolecules() = 1, nChains() = 0, nResidues() = 288, nAtoms() = 4644 )) to start the creation of a new System. You 
need to use a more detailed input file. (call sire.error.get_last_error_details() for more info)
...
OSError: Failed to read molecules from: ['protein_pdb2gmx.pdb', 'topol.top']
```
If I try to read in just the PDB file then this error no longer exists.

The [files are located here
](https://drive.google.com/drive/folders/1wlpy4p9zk7OFA6JnLM122x7rLAQ4W7Y7?usp=sharing)
I'm a little stuck as to what to try next, any suggestions would be welcome.

**Comment by lohedges** [comment]
Both the `GROTOP` and `PDB` formats are able to be parsed independently in order to create a system, for example:

```python
imprort BioSimSpace as BSS

system_top = BSS.IO.readMolecules(["topol.top"])
system_pdb = BSS.IO.readMolecules(["protein_pdb2gmx.pdb"])
```

When two (or more) parsers are capable of creating a system, then one will be chosen as the _leader_, i.e. to create the initial system, then the others _follow_, i.e. add additional information to this system. I imagine that you are seeing a failure due to the particular order of the parsing on the server. For example, perhaps `GROTOP` is able to follow `PDB`, but not the opposite. (I think that `GROTOP` followed by something else assumes the same atom naming, which isn't the case here.)

If you just want to apply all of the properties associated with the topology to the PDB system, or vice-versa, then you can just load individually and use `makeCompatibleWith`, e.g:

```python
# This molecule has properties from both of the molecules loaded above. This will only work
# if the topology of the molecules is the same.
mol_top = system_top0]
mol_pdb = system_pdb[0]

# GROTOP properties.
mol_top._sire_object.propertyKeys()
['particle_type',
 'connectivity',
 'element',
 'bond',
 'LJ',
 'space',
 'time',
 'fileformat',
 'dihedral',
 'atomtype',
 'charge_group',
 'mass',
 'forcefield',
 'angle',
 'intrascale',
 'charge']

# PDB properties.
mol_pdb._sire_object.propertyKeys()
['occupancy',
 'connectivity',
 'element',
 'beta_factor',
 'space',
 'time',
 'fileformat',
 'formal_charge',
 'is_het',
 'is_ter',
 'coordinates',
 'insert_code',
 'alt_loc']

# Try to add the PDB properties into the GROTOP molecule.
mol_top.makeCompatibleWith(mol_pdb)

# Combined properties. Note that the order of operation will set the precedence if two molecules
# share a property.
mol_top._sire_object.propertyKeys()
['bond',
 'dihedral',
 'mass',
 'fileformat',
 'charge_group',
 'time',
 'angle',
 'alt_loc',
 'coordinates',
 'occupancy',
 'insert_code',
 'LJ',
 'is_ter',
 'formal_charge',
 'particle_type',
 'charge',
 'element',
 'is_het',
 'space',
 'intrascale',
 'connectivity',
 'atomtype',
 'forcefield',
 'beta_factor']
```
I'll see if I can trigger your issue locally in case this isn't what's going on.

**Comment by noahharrison64** [comment]
Hi @lohedges , 

Thanks for the info, I think this has helped me resolve the issue! Good to understand the inner workings of BSS/Sire so I won't have to troubleshoot as much.

Thanks,
Noah

**Comment by lohedges** [comment]
No problem, glad it was useful. Looking more closely at error message it does look like a problem on the PDB side:

```
There is not enough information in this parser (PDB2( 
nMolecules() = 1, nChains() = 0, nResidues() = 288, nAtoms() = 4644 )) to start the creation of a new System.
```

Could you try calling ` sire.error.get_last_error_details()` on the server to get the full trace? (You'll just need to add `import sire` first.)

**Comment by noahharrison64** [comment]
The issue was that sire was unable to find the GMX forcefield files when loading the topology file! This became clear from the sire error details that were produced when I tried to load just the .top file into a system. To resolve I had to set GROMACS_PATH env explicitly, which is odd since I haven't had to do this before but I'm going to assume something must have gone wrong when setting up the dependencies on the server!

Cheers!

**Comment by lohedges** [comment]
Ah interesting. By default the `GROMACS_PATH` variable is generated from data prefix obtained by calling `gmx`, e.g.:

```
 gmx
                 :-) GROMACS - gmx, 2022.4-plumed_2.9.0_dev (-:

Executable:   /usr/local/gromacs/bin/gmx
Data prefix:  /usr/local/gromacs
Working dir:  /home/lester
Command line:
...
```

You can query what BioSimSpace has found by printing the `BSS._gmx_path` variable, e.g.:

```python
In [1]: import BioSimSpace as BSS

In [2]: BSS._gmx_path
Out[2]: '/usr/local/gromacs/share/gromacs/top'
```

Perhaps this is being reported incorrectly on the server for some reason, or the path isn't readable. You can always set this explicitly when loading molecules by using the `property_map`, e.g.:

```python
 BSS.IO.readMolecules(['protein_pdb2gmx.pdb', 'topol.top'], property_map={"GROMACS_PATH": "/path/to/gromacs/top/files"})
```

**Comment by noahharrison64** [comment]
Okay cool I'll do some investigating to see if I can figure out why it wasn't working automatically, thanks again.

**Comment by lohedges** [comment]
My guess is that `gmx` isn't working, e.g. it might need to be recompiled due to an updated to a library or driver on the server. We check that `gmx` exists, but don't do anything if it doesn't run, in which case the `_gmx_path` would be set to `None`. It might be useful if we add a warning in this case.
