### ISSUE TITLE
Passing kwargs to LOMAP using Align.generateNetwork()

### ISSUE THREAD

**Issue by DreamCykl** [OpenBioSim/biosimspace#13]
Hi,

I'm looking to use BioSimSpace to run FEP calculations, however I would like to generate a minimal spanning graph using a radial network. This is an option in the original lomap implementation - see [example here](https://github.com/OpenFreeEnergy/Lomap/blob/main/examples/example_radial_graph.py). It appears like there's no functionality to request a radial graph using BioSimSpace, would it be straightforward to pass kwargs to LOMAP in order to achieve this?

**Comment by lohedges** [comment]
Hello there,

Thanks for your question. Yes, it shouldn't be a problem to add `**kwargs` to the `generateNetwork` function. This was originally written for a specific use case for a workshop that we gave and hasn't been updated (or used much) since. The only issue is making sure that the `**kwargs` takes precedence, i.e. it overwrites any default options that we pass through to `DBMolecules`, which shouldn't be too tricky.

I'll take a look when I can.

**Comment by lohedges** [comment]
Hi again,

This is now implemented on a feature branch [here](https://github.com/OpenBioSim/biosimspace/tree/feature_lomap_kwargs). I just need to run a few tests to make sure that tutorials based on our existing code still work before merging. If you want to try it out, you can always install from source using the branch.

Cheers.

**Comment by DreamCykl** [comment]
Hi @lohedges ,

Thank you for including that feature. I will hopefully get round to testing this very soon. I appreciate the speed at which you integrated this!

Cheers.

**Comment by lohedges** [comment]
No problem. The thing that I've not yet checked is whether there are other assumptions in the function, e.g. processing the LOMAP output, making plots, etc., that are conditioned on certain defaults having been set, i.e. will these still work if the user overrides certain parameters with `**kwargs`. If this is the case, then I can try to catch this and disable certain functionality.

**Comment by DreamCykl** [comment]
Hey,

I've been trying this functionality and while nothing appears to break when passing the radial argument to generateNetwork(), LOMAP seems to be unable to actually generate a radial network... Have you had any success with it? Obviously this is an issue I should raise in the OpenFE repo.

Thanks.

**Comment by lohedges** [comment]
Hi there,

It's not something that I've tried myself. I'll give it a go and see what happens. Is the radial option the only extra thing that you're passing in?

**Comment by DreamCykl** [comment]
I tried with radial and also supplying a hub ligand. I tried running directly with LOMAP to no success either, so looks like an issue I should raise over there!

**Comment by jmichel80** [comment]
Thanks for the update @DreamCykl  - I will reopen the issue and it would be great if you can cross-reference to an OpenFE forum so we get to the bottom of this.
