### ISSUE TITLE
[BUG] genion fails with crystallographic water in a protein-ligand system

### ISSUE THREAD

**Issue by cespos** [OpenBioSim/biosimspace#141]
**Describe the bug**
In my system, I have a protein with two crystallographic waters bound to a ligand.
BSS.Solvent.solvate() fails with the following error:
![image](https://github.com/OpenBioSim/biosimspace/assets/31316943/66ca810f-7174-441c-9c3f-13bf07f493f0)

Looking into the genions.err, I found the error message:
![image](https://github.com/OpenBioSim/biosimspace/assets/31316943/ccdd1bdb-7a76-4d56-b3a6-80dcc81568db)

And this is because in the input system, I have in order:
- protein 
- crystallographic waters
- ligand

Therefore, when solvent waters are added, genions sees water molecules that are not continuous but with a ligand in between.
How to best deal with this?

**To Reproduce**
```
import BioSimSpace as BSS

protein_coord = BSS.IO.readMolecules('protein.pdb')[0]
ligand_coord = BSS.IO.readMolecules('ligand.sdf')[0]

protein = BSS.Parameters.parameterise(protein_coord , 'ff14SB', water_model='tip3p').getMolecule()
ligand = BSS.Parameters.parameterise(ligand_coord, 'gaff2').getMolecule()
system = protein + ligand

box = [100 * BSS.Units.Length.angstrom] * 3
angles = [100 * BSS.Units.Angle.degree] * 3
solvated = BSS.Solvent.solvate('tip3p', system, box=box, angles=angles, work_dir='tmp')
```

**Expected behavior**
BSS.Solvent.solvate() should not fail

**(please complete the following information):**
 - Ubuntu
 - Version of Python: 3.10.12
 - Version of BioSimSpace: 2023.3.0
 - I confirm that I have checked this bug still exists in the latest released version of BioSimSpace: [yes/no] no (not in the dev version)

**Comment by cespos** [comment]
I just noticed that this issue is related to issue #67

**Comment by lohedges** [comment]
Thanks. I am away at the moment and will take a look next week. We do have code to deal with existing waters, i.e. to make sure that they are contiguous, but it is clearly failing in certain cases.

**Comment by cespos** [comment]
Thanks Lester! 

This solved it for me:

![image](https://github.com/OpenBioSim/biosimspace/assets/31316943/aa6e1a4c-6f29-440b-a063-c33a98692bef)

**Comment by lohedges** [comment]
Are you able to share the example system that triggers the error? I'm guessing that the issue is caused by one of the following:

* Non-standard water naming.
* Waters embedding in the protein, i.e. the are not separate molecules, so are not detected by our water finding code.

Cheers.

**Comment by cespos** [comment]
I cannot share the system but I can send you a screenshot of the PDB showing ions, water molecules, and the protein terminal residue.

![image](https://github.com/OpenBioSim/biosimspace/assets/31316943/cd0c8a82-768b-4401-8daf-4cbbadf4ef1a)

**Comment by lohedges** [comment]
Thank you, this is very helpful. As shown, the first crystal water is combined with other atoms, i.e. `MG`, `CA`, and `CA`. We'll need to add some logic to search for water molecules within a structure, rather than just as self-contained molecules. I'll see if I can find another example, or make one myself.
