### ISSUE TITLE
Default SOMD Options Give Extremely Poor Performance

### ISSUE THREAD

**Issue by fjclark** [OpenBioSim/biosimspace#18]
Hi,

The default SOMD `n_cycles` and `nmoves` options are resulting in very poor performance for me. Running the script shown [here](https://github.com/OpenBioSim/biosimspace/issues/17#issue-1619116837) with the GROMACS process replaced with the SOMD process results in the following simfile options:

```
save coordinates = True
ncycles = 500
nmoves = 100
ncycles_per_snap = 1
buffered coordinates frequency = 0
timestep = 2.00 femtosecond
reaction field dielectric = 78.3
cutoff type = cutoffperiodic
cutoff distance = 8 angstrom
barostat = True
pressure = 1.00000 atm
thermostat = True
temperature = 300.00 kelvin
gpu = 0
```

As a result of the extremely large number of cycles for few moves, my GPU utilisation drops from ~ 90 % (with `nmoves = 50000` and `ncycles=1`) to ~ 4 % and simulations become extremely slow. Could the number of cycles please be reduced to avoid this performance hit? Thanks.

**Comment by lohedges** [comment]
Unfortunately this is the issue trying to make SOMD behave like the other engines that we support for reporting purposes, i.e. so I can have a consistent implementation of `report_interval` and `restart_interval` across all engines, so it can seem interoperable. SOMD only really performs well for _long_ simulations where you have few cycles.

This has always been an issue and I've tried to mitigate it as much as possible. We could just treat SOMD completely differently, so that it has its own defaults, but then a user might be confused why the get a different sized trajectory, or less frequent reporting. This _should_ all be fixed when we start work on SOMD2.

**Comment by fjclark** [comment]
Right, thanks for the clarification. However, I still don't understand - if I set the simulation length to 5 ns, this only increases `ncycles`, while `nmoves` stays the same, meaning that performance seems equally bad:

```
save coordinates = True
ncycles = 25000
nmoves = 100
ncycles_per_snap = 1
buffered coordinates frequency = 0
timestep = 2.00 femtosecond
reaction field dielectric = 78.3
cutoff type = cutoffperiodic
cutoff distance = 8 angstrom
barostat = True
pressure = 1.00000 atm
thermostat = True
temperature = 300.00 kelvin
gpu = 0
```

**Comment by lohedges** [comment]
You've just increased `runtime` without increasing `report_interval` and `restart_interval`?

**Comment by jmichel80** [comment]
potentially there is a workaround by setting buffered coordinates frequency such that after one cycle several frames are written to the trajectory.

**Comment by lohedges** [comment]
> potentially there is a workaround by setting buffered coordinates frequency such that after one cycle several frames are written to the trajectory.

This is what it should do. The buffering should be adjusted appropriately relative to the chosen `restart_interval` and `report_interval`.

**Comment by fjclark** [comment]
Thanks for the examples.

> You've just increased `runtime` without increasing `report_interval` and `restart_interval`?

Yes, that's what I did. I was assuming that you meant performance with default options over a long simulation would be reasonable, but from this I assume that the user always has to dramatically change the restart and report interval to get usable performance, regardless of the runtime? e.g. the last example above, run on a GPU
```
protocol = BSS.Protocol.Production(runtime=2*BSS.Units.Time.nanosecond, restart_interval=200, report_interval=200)
process = BSS.Process.Somd(system, protocol, work_dir="output", platform="CUDA")
```
still gives poor performance due to `nmoves=200`. Am I understanding correctly?

**Comment by fjclark** [comment]
OK, thanks very much for clarifying.
