### ISSUE TITLE
Does making one molecule compatible with another lead to the coordinates changing?

### ISSUE THREAD

**Issue by DreamCykl** [OpenBioSim/biosimspace#212]
Hi,

I am doing some interconversions between BSS and RDKit molecules. I'm first converting simulated BSS ligands to RDMols in order to run constrained alignment (i.e. a 'flexible'-ish alignment where the cores are superimposed and the rest of the molecule is allowed to vary). I know there is a flexible alignment implemented in BSS but I had mixed success when testing it a while back.
When I try and convert my aligned RDMol back to BSS I run the makeCompatibleWith() method to copy back the forcefield parameters from the simulated ligand. This however appears to change the coordinates of the aligned molecule. Is this intended? I looked at the docs and thought it shouldn't modify the coordinates.

Here's the code, simplified to just outline the process I'm running. I'm working with proprietary molecules and hence haven't included example files, but I can re-run with examples and provide if necessary. 

```py
# Files that contain bond info and are provided to the initial parameterisation process
rdmol_a = Chem.SDMolSupplier('lig_a.sdf')[0]
rdmol_b = Chem.SDMolSupplier('lig_b.sdf')[0]

# Files below are extracted from a simulation frame
bssmol_a = BSS.IO.readMolecules(['lig_a.top', 'lig_a.pdb']).getMolecule(0)

# Files below are from the parameterisation process and haven't been simulated
bssmol_b = BSS.IO.readMolecules(['lig_b.top', 'lig_b.pdb']).getMolecule(0)

# Convert bssmol_a to an rdmol
# Use rdmol_a to provide bond info to the bss_rdmol_a object, since this is lost during conversion from BSS mol to RDMol
bss_rdmol_a = BSS.Convert.toRDKit(bssmol_a).toMolecule()
bss_rdmol_a = AllChem.AssignBondOrdersFromTemplate(
    rdmol_a,
    bss_rdmol_a
 )

# Align mol_b onto mol_a
# We use bss_rdmol_a since this contains the coordinates we want to align rdmol_b to, as well as the necessary bond info that the PDB from the simulation doesn't contain. 
aligned_rdmol_b = align_ligands(
    bss_rdmol_a,
    rdmol_b
)

aligned_bssmol_b = BSS.Convert.toBioSimSpace(rdmol_b).toMolecule()
BSS.IO.saveMolecules("pre_makeCompat", aligned_bssmol_b, ['pdb'])
aligned_bssmol_b.makeCompatibleWith(bssmol_b)
BSS.IO.saveMolecules("post_makeCompat", aligned_bssmol_b, ['pdb'])
```

The coordinates of pre_makeCompat.pdb and post_makeCompat.pdb  do not match. It appears that when using makeCompatibleWith() the aligned_bssmol_b coordinates (which should be aligned to lig_a) are switched to the bssmol_b coordinates  (which are unaligned).  Perhaps this is the intended function, but that's not clear to me from the documentation.

A work around would be for me to copy the coordinates of the aligned_bssmol_b onto the bssmol_b object (since the forcefield parameters / properties already exist here) although I can't figure out an easy way to do this.

Any advice would be greatly appreciated.

**Comment by lohedges** [comment]
By default it will overwrite any existing properties with the same name. To change this behaviour, just pass `overwrite=False`, in which case only _new_ properties will be copied across. The API docs are [here](https://biosimspace.openbiosim.org/api/generated/BioSimSpace._SireWrappers.Molecule.html#BioSimSpace._SireWrappers.Molecule.makeCompatibleWith). 

The intended use of this method is to copy new properties into an existing molecule while preserving its topology, e.g. copying force field parameters back into a molecule after parameterisation without losing the topology and attributes from the original PDB file.

**Comment by lohedges** [comment]
That's right. For FEP `molecule0` is the reference molecule, i.e. what would be simulated when the lambda parameter is 0, If you want to do the perturbation in the _reverse_ direction, then you can just invert the mapping and swap the order of the molecules in the merge function.

```python
inv_mapping = {v:k for k,v in mapping.items()}
```

**Comment by lohedges** [comment]
> Ok thank you, that's what I thought. If I'm using BSS.Align.matchAtoms molecule0 should also be molecule0 in .merge()?

Yes, otherwise your mapping dictionary will be the wrong way around.

> I only ask because the docs suggest molecule0 is aligned to molecule1 prior to matching atoms, and in my case I want to merge molecule1 to molecule0, retaining the coordinates of molecule0 (and therefore I don't want to align 0 -> 1) But am I right in thinking alignment is only required for atom matching, and won't actually effect the coordinates used during merge?

The alignment is required since you don't want the molecules to be in different positions during the perturbation, i.e. you don't want atoms to appear miles away from the reference molecule. It sounds like you just want to do everything the other way around? If so, just swap the molecules throughout, i.e. get a mapping from 1 to 0, then align 1 to 0, then merge with 1 as the reference.
