### ISSUE TITLE
Conda Installation of Dev Version Fails

### ISSUE THREAD

**Issue by fjclark** [OpenBioSim/biosimspace#229]
**Describe the bug**
While attempting to test SOMD2, I found I couldn't install biosimspace from the `openbiosim/label/dev` channel. Running `mamba env create -f environment.yaml` on the SOMD2 env file produced:

![image](https://github.com/OpenBioSim/biosimspace/assets/90148170/7644a462-c0c5-408c-9010-723364fcdec9)

I double-checked that
```
mamba create -n temp "python=3.10" 
mamba install -n temp -c openbiosim/label/dev biosimspace
```
also fails.

The installation worked when I changed the channel to `openbiosim`.

 - OS: Ubuntu 20.04

**Comment by lohedges** [comment]
This is because there have been no commits to `devel` since the 2023.5.0 release and I think the old Sire development packages have been moved to our archive. I'll trigger a manual build now so you should have a `2024.1.0.dev` package, which will pull in same dev version for Sire.

**Comment by lohedges** [comment]
Actually, it appears that the 2023.4.1/2.dev Sire packages are still there, so it seems that the pinning isn't working. Will trigger a build anyway.

**Comment by chryswoods** [comment]
No - this was my fault. The dev packages on conda are 2024.1.0.dev - the 2023.5.0.dev packages have been removed.

**Comment by lohedges** [comment]
No problem. I'll just make a note to do a dev build as soon as I create the new tag during the release process. Regardless of the space issue, it makes sense that we don't keep old dev packages knocking around for too long.

**Comment by fjclark** [comment]
Thanks for sorting this!
