### ISSUE TITLE
reduceBoxVectors does not prevent RuntimeError: Periodic box vectors must be in reduced form

### ISSUE THREAD

**Issue by fjclark** [OpenBioSim/biosimspace#238]
**Describe the bug**

I am attempting to run some inputs generated with an old version of Sire and BioSimSpace with the latest devel versions of Sire and BioSimSpace. I loaded all old systems, called `reduceBoxVectors`, and saved the new systems over the old ones. However, I still get the error 
![image](https://github.com/OpenBioSim/biosimspace/assets/90148170/9bc62e7e-c8db-4ed2-9d1e-c0765cfc11d6)
with many of these systems.

How should I fix the box vectors? I am currently unable to set things up from scratch due to https://github.com/OpenBioSim/biosimspace/issues/211 .

**To Reproduce**

The input files to reproduce this issue are here: [gh_issue.tar.gz](https://github.com/OpenBioSim/biosimspace/files/14184205/gh_issue.tar.gz). Change the paths in `somd.cfg` and run  `somd-freenrg -c somd.cfg`. I have called reduceBoxVectors on this system.

 - OS: Ubuntu 22.04
 - Version of Python: 3.11.7
 - Version of BioSimSpace: Latest dev version, installed from gh repo, compiled latest version of sire this morning
 - I confirm that I have checked this bug still exists in the latest released version of BioSimSpace: yes

Thanks!

**Comment by lohedges** [comment]
That's annoying. I'll try to debug tomorrow morning. Have you tried manually applying OpenMM`s internal reduction instead, e.g. as we do for the OpenMM setup [here] (https://github.com/OpenBioSim/biosimspace/blob/devel/python%2FBioSimSpace%2FProcess%2F_openmm.py#L460). This should be equivalent to our reduction, though. (I tested they were the same.) OpenMM does apply _full_ numerical precision when checking for reduced form, though, so it's very easy to trigger the error when loading from file.

Another option is to use the `bias` keyword when using our reduction function. This will bias towards left or right tilting boxes, so may allow you to round in the direction that satisfies OpenMM's conditional. (This is what we used previously, but it still doesn't reliably work in all cases.) You should only need to use a small positive or negative value, depending on which way you want to bias. (Something on the order of the coordinates precision is normally okay.)

**Comment by lohedges** [comment]
That's annoying. I'll try to debug tomorrow morning. Have you tried manually applying OpenMM`s internal reduction instead, e.g. as we do for the OpenMM setup [here] (https://github.com/OpenBioSim/biosimspace/blob/devel/python%2FBioSimSpace%2FProcess%2F_openmm.py#L460). This should be equivalent to our reduction, though. (I tested they were the same.) OpenMM does apply _full_ numerical precision when checking for reduced form, though, so it's very easy to trigger the error when loading from file.

Another option is to use the `bias` keyword when using our reduction function. This will bias towards left or right tilting boxes, so may allow you to round in the direction that satisfies OpenMM's conditional. (This is what we used previously, but it still doesn't reliably work in all cases.) You should only need to use a small positive or negative value, depending on which way you want to bias. (Something on the order of the coordinates precision is normally okay.)

One other thought is that you may need to rotate before reducing, e.g. by calling `rotateBoxVectors`.

**Comment by lohedges** [comment]
It runs if you rotate and then reduce, e.g.:

```python
import BioSImSpace as BSS

system = BSS.IO.readMolecules("*7")
system.rotateBoxVectors()
system.reduceBoxVectors()

BSS.IO.saveMolecules("somd", system, "rst7")
```

However, during the first cycle I see:

```
NaN or Inf has been generated along the simulation
```

I wonder if the rotation isn't being applied correctly for some reason. (Minimisation is fine, though.)

The reason why we need to both rotate and reduce is that, although the vectors were in reduced form, OpenMM (like some other engines) has additional constraints on the orientation of the lattice vectors, i.e. which lies along the x axis, which in the x-y plane, etc.

I'll keep debugging to see if I can work out why it crashes. (Presumably it didn't using the original input?)

**Comment by fjclark** [comment]
Thanks very much for the explanation.

No, I've run many (~50) simulations starting from the original input without getting any crashes. Thanks.

**Comment by lohedges** [comment]
Do you have the original input, i.e. pre the reduction that you did? I'd like to see if it works using that. I did a rotation and reduction on the inputs in the archive and noticed that reducing (presumably again) changed the box, so it was at an instability. Perhaps it would work if it wasn't reduced twice. (The order of the rotation and reduction can matter too, so I can't just rotate the reduced box.)

I'll have a look at the rotated systems to see if something funky is going on. It should rotate all vector properties accordingly, but perhaps it's not working correctly for some reason. (I have a basic test of this.)

**Comment by lohedges** [comment]
Interestingly the boxes are different in the two rst7 files. Presumably the GROMACS equilibration was NPT so the box has fluctuated:

```
tail *rst7
==> stable_pre_reduction.rst7 <==
  15.7100000  18.4200000  19.6600000  22.5300000  42.4000000  57.7600000
  27.0600000  17.2600000  44.8500000  63.5800000  23.0500000  45.3900000
   5.8000000  13.0900000   7.2400000  44.7100000  14.4300000  27.0000000
  63.8500000  29.4300000  55.0400000  45.5100000  32.0600000  43.6300000
   8.7100000   6.3200000   6.8200000  35.2400000  63.0000000   0.1600000
  30.5300000  55.9300000   6.6700000  17.2300000  17.7800000   7.6800000
  36.8500000   9.0700000  34.1500000  36.5300000  10.9100000  16.8100000
  67.6900000   7.0200000  56.7700000  35.9500000  22.7100000  49.2300000
  23.0500000  55.4000000  18.5400000
  73.4685000  63.6275442  73.4685126  73.4555835 119.9999493  89.5520932

==> unstable_pre_reduction.rst7 <==
  53.5700000  30.8700000   9.1400000  33.7500000  42.3500000   4.8400000
  17.6700000  39.9200000  34.1500000   8.1500000  49.4100000  39.6200000
  64.6600000  26.6600000  11.6400000   2.1700000  61.9700000  52.2700000
  19.4100000  27.8300000  56.7800000  37.5700000  17.5900000   8.7800000
  16.7400000  35.5100000   4.0300000  21.5300000   1.5900000  58.1700000
   1.5800000   0.4900000  28.3700000  35.0500000  35.7400000  14.2100000
  29.4300000  15.9400000  18.2200000  71.9300000  24.3900000  57.9600000
  68.0100000  53.5800000  41.0900000  63.2800000  24.5400000  21.3800000
  25.0900000  28.6900000  29.3300000
  73.4884000  63.6448452  73.4884669  72.9877837  60.0000301  89.5520349
```

Running with `unstable_pre_reduction.rst7` gives the "box vectors aren't in reduced form" error, whereas using `stable_pre_reduction.rst7` runs fine with no crashes.

Tying to rotate and reduce the unstable box allows OpenMM to run, but the energies are crazy and the simulation immediately blows up:

```
Initial energy: 2.20926e+13 kcal mol-1
###=======================Minimisation========================###
Running minimization.
Tolerance for minimization: 1
Maximum number of minimization iterations: 1000
Energy after the minimization: 2.25576e+14 kcal mol-1
Energy minimization done.
###===========================================================###

###====================somd-freenrg run=======================###
Starting somd-freenrg run...
25000 moves 2 cycles, 200 ps simulation time

Cycle =  1

NaN or Inf has been generated along the simulation
```

The energies are similarly large for the stable coordinate file. Presumably the rotation isn't working correctly here. I'll try to debug what's gone wrong.

**Comment by lohedges** [comment]
I have an idea for the issue. When performing the rotation the lattice vectors are re-ordered to satisfy the constraints that I mentioned before. However, the rotation matrix applies to the re-ordered vectors, not the original ones. I'll see if I can change that (or store the reordering) to see if it fixes things.

**Comment by lohedges** [comment]
Weirdly I'm now seeing the following exception whenever I try to run your example:

```python
RuntimeError: SireBase::duplicate_property: More than one forcefield contains the property (space), and it has a different value in these forcefields. You will have to search for this property individually in each forcefield (e.g. using the ForceFields::forceFieldsWithProperty(...) member function). (call sire.error.get_last_error_details() for more info)
```

This seems to be after the system is setup via `setupForceFieldsFreeEnergy`, i.e. if you then call `system.property("space")` you get the above error. I wasn't seeing this yesterday, so I'm not sure what's changed...

(This doesn't happen for other `somd-freenrg` simulations that I've tested, e.g. hydration free energy perturbations for comparison with `somd2`.)

**Comment by lohedges** [comment]
I've done a rebuild of the Sire branch and it's now working :man_shrugging:

**Comment by lohedges** [comment]
I thought I'd try minimising with Sire prior to writing the files to see if that works. This does the conversion to OpenMM in the C++ layer, where I discovered they do comparisons to _exact_ numerical precision, e.g. from [here](https://github.com/openmm/openmm/blob/71f4b3fcb0b07d0fe41302df03f5373c8424cefa/openmmapi/src/System.cpp#L124-L130)

```c++
void System::setDefaultPeriodicBoxVectors(const Vec3& a, const Vec3& b, const Vec3& c) {
    if (a[1] != 0.0 || a[2] != 0.0)
        throw OpenMMException("First periodic box vector must be parallel to x.");
    if (b[2] != 0.0)
        throw OpenMMException("Second periodic box vector must be in the x-y plane.");
    if (a[0] <= 0.0 || b[1] <= 0.0 || c[2] <= 0.0 || a[0] < 2*fabs(b[0]) || a[0] < 2*fabs(c[0]) || b[1] < 2*fabs(c[1]))
        throw OpenMMException("Periodic box vectors must be in reduced form.");
```

This is even more stringent that the Python checks (which evaluates the reduced form in a different way), so it looks like BioSimSpace reduced boxes wouldn't be convertible to OpenMM via `sire.convert`. I'll see if I can just zero the components if they are sufficiently small.

**Comment by lohedges** [comment]
Okay, I've got it to work by setting the appropriate components to zero if they are sufficiently close. With that change, the solution to get your old systems to work is as follows:

```python
import BioSimSpace as BSS
import sire as sr

# Load the old system.
system = BSS.IO.readMolecules("somd.*7")

# Rotate and reduce the box.
system.rotateBoxVectors()
system.reduceBoxVectors()

# Convert to a Sire system and minimise.
sire_system = sr.system.System(system._sire_object)
m = sire_system.minimisation()
m.run()
m.commit()

# Save the updated coordinate file.
sr.save(sire_system, "somd.rst7")
```

**Comment by fjclark** [comment]
Brilliant - thanks very much.

**Comment by lohedges** [comment]
The triclinic "fix" is now merged into Sire `devel`. (I say "fix", since it's reallly an OpenMM precision issue.) Let me know if you have any further problems and feel free to close when you are happy.

**Comment by fjclark** [comment]
Perfect - thanks for sorting this so quickly.
