### ISSUE TITLE
[BUG]Is there a bug for  funnel correction when estimating the average area of the restraint?

### ISSUE THREAD

**Issue by zheqiang-zhong** [OpenBioSim/biosimspace#246]
Dear Developer,

The line when calculating the average area is:
` # Estimate the average area of the restraint (in Angstrom squared).
        area = (volume / proj_max).angstroms2()`

Do you think it should be:
`` # Estimate the average area of the restraint (in Angstrom squared).
        area = (volume / (proj_max - proj_min)).angstroms2()``

to get the correct surface of the cylinder.

Thanks and best regards,

**Comment by lohedges** [comment]
Thanks for reporting, I believe you are correct. This was adapted from @dlukauskis' original analysis notebook, which I can't seem to find.
