### ISSUE TITLE
[BUG] prepareFEP.py calls `BSS.IO.saveMolecules` with an missing `match_water` parameter

### ISSUE THREAD

**Issue by nigel-palmer-cresset** [OpenBioSim/biosimspace#291]
[prepareFEP.py](https://github.com/OpenBioSim/biosimspace/blob/240e2f1565e2251dcf6c873476a225da9ddb53aa/nodes/playground/prepareFEP.py#L272) has the following code

```
BSS.IO.saveMolecules(
    "merged_at_lam0.pdb",
    merged,
    "PDB",
    {"coordinates": "coordinates0", "bond": "bond0", "element": "element0"},
)
```

This fails due to [biosimspace/python/BioSimSpace/IO/_io.py::saveMolecules](https://github.com/OpenBioSim/biosimspace/blob/240e2f1565e2251dcf6c873476a225da9ddb53aa/python/BioSimSpace/IO/_io.py#L594) requiring an `match_water` parameter.

Changing it to the following fixes the problem.

```
BSS.IO.saveMolecules(
    "merged_at_lam0.pdb",
    merged,
    "PDB",
    property_map={"coordinates": "coordinates0", "bond": "bond0", "element": "element0"},
)
```

Thanks

**Comment by lohedges** [comment]
Thanks for reporting. This is actually because `prepareFEP` is passing keyword arguments, e.g. the `property_map` as positional arguments. There is no need to pass `match_water`.

I'll update the script tomorrow.

**Comment by lohedges** [comment]
Sorry, couldn't see your code snippet on my phone. That's the correct solution, i.e. passing the property map as a kwarg.
