### ISSUE TITLE
ABFE tutorial question

### ISSUE THREAD

**Issue by jnutyj** [OpenBioSim/biosimspace#325]
Hi OpenBioSim, 
I don't know whether I should post this question here, but I hope someone could help me answer it.
I recently went through the tutorial in the notebook(https://try.openbiosim.org/). It is an excellent tutorial!!!
But I have one question for the absolute binding free energy in 04_FEP/03_ABFE. When it needs calculate the free leg, I saw the code that  it does not have much difference between bound leg and free leg. 

Shouldn't the system only contain ligand (without protein) in the free leg for calculation? But the code still uses "restraint.system".  I think the restraint.system contains both MIF protein and ligand.  In addition, in the free leg, I think it should not contain restraint, am I correct? 
Thank you!
Best regards,

**Here is the copy from notebook:**
**_Example: Setting up the bound leg discharge and vanish stages with a 1 fs timestep_**
Set up discharge stage
lam_vals_discharge = [0.000, 0.143, 0.286, 0.429, 0.571, 0.714, 0.857, 1.000]

discharge_protocol = BSS.Protocol.FreeEnergy(
    runtime=6 * BSS.Units.Time.nanosecond,
    timestep=1*BSS.Units.Time.femtosecond, 
    lam_vals=lam_vals_discharge,
    perturbation_type="discharge_soft",
)
discharge_fe_calc = BSS.FreeEnergy.AlchemicalFreeEnergy(
    restraint.system,
    discharge_protocol,
    engine="somd",
    restraint=restraint,
    work_dir="output/discharge",
)

Set up vanish stage
lam_vals_vanish = [0.000, 0.025, 0.050, 0.075, 0.100, 0.125, 0.150, 0.175, 0.200, # We need a lot of these to
                   0.225, 0.250, 0.275, 0.300, 0.325, 0.350, 0.375, 0.400, 0.425, # ensure sufficient overlap
                   0.450, 0.475, 0.500, 0.525, 0.550, 0.575, 0.600, 0.625, 0.650, # between windows!
                   0.675, 0.700, 0.725, 0.750, 0.800, 0.850, 0.900, 0.950, 1.000] 

vanish_protocol = BSS.Protocol.FreeEnergy(runtime=6*BSS.Units.Time.nanosecond, 
                                          timestep=1*BSS.Units.Time.femtosecond, 
                                          lam_vals=lam_vals_vanish, 
                                          perturbation_type="vanish_soft")

vanish_fe_calc = BSS.FreeEnergy.AlchemicalFreeEnergy(restraint.system, 
                                                     vanish_protocol, 
                                                     engine='somd', 
                                                     restraint=restraint, 
                                                     work_dir='output/vanish')

**_Example: Setting up the free leg_**
lam_vals_discharge_free = [0.000, 0.143, 0.286, 0.429, 0.571, 0.714, 0.857, 1.000]

free_discharge_protocol = BSS.Protocol.FreeEnergy(runtime=6*BSS.Units.Time.nanosecond, 
                                                  lam_vals=lam_vals_discharge_free, 
                                                  perturbation_type="discharge_soft")

free_discharge_fe_calc = BSS.FreeEnergy.AlchemicalFreeEnergy(restraint.system,
                                                             free_discharge_protocol,
                                                             engine='somd',
                                                             restraint=restraint,
                                                             work_dir='output/free_discharge')

lam_vals_vanish_free = [0.000, 0.028, 0.056, 0.111, 0.167, 0.222, 0.278, 0.333, 0.389, 0.444, 
                        0.500, 0.556, 0.611, 0.667, 0.722, 0.778, 0.889, 1.000]

free_vanish_protocol = BSS.Protocol.FreeEnergy(runtime=6*BSS.Units.Time.nanosecond, 
                                               lam_vals=lam_vals_vanish_free,
                                               perturbation_type="vanish_soft")

free_vanish_fe_calc = BSS.FreeEnergy.AlchemicalFreeEnergy(restraint.system,
                                                          free_vanish_protocol,
                                                          engine='somd', 
                                                          restraint=restraint,
                                                          work_dir='output/free_vanish')

**Comment by fjclark** [comment]
Hi @jnutyj. Thanks - I'm glad they're helpful! 

You are completely correct - I've been sloppy when copying things. Apologies for the confusion - I don't know how I missed this before. As you say, you just need to swap out the system for one containing only the ligand in a box of water, and set `restraint=None`. I am just about to go on leave for a few weeks, but I will correct this when I'm back.

Cheers,
Finlay

**Comment by jnutyj** [comment]
Thank you for your answer!
I really like the tutorial and it is very easy to understand.
