### ISSUE TITLE
Antechamber Warning Message Inconsistent with the Code

### ISSUE THREAD

**Issue by fjclark** [OpenBioSim/biosimspace#4]
Hello,

Some of the tests were failing due to an issue which was my fault (I had amber in my path ahead of the antechamber in my conda environment), but there seems to be a typo in the error messages: the [errors stated that I required antechamber >= 20](https://github.com/OpenBioSim/biosimspace/blob/9188c699fdea5861bf51264c696ff4ef2ec692a2/python/BioSimSpace/Sandpit/Exscientia/Parameters/_parameters.py#L489), which I had, but in fact [the code was checking for antechamber >= 22](https://github.com/OpenBioSim/biosimspace/blob/9188c699fdea5861bf51264c696ff4ef2ec692a2/python/BioSimSpace/Sandpit/Exscientia/Parameters/_parameters.py#L474). Could this please be made consistent with whichever version is required?

Thanks very much.

**Comment by lohedges** [comment]
Thanks for catching this. I recently updated the requirement because OpenFF requires a more recent version but apparently haven't updated the message. Cheers.
