### ISSUE TITLE
[BUG] SOMD failure due to "inverse friction" configuration value

### ISSUE THREAD

**Issue by lohedges** [OpenBioSim/biosimspace#45]
SOMD is currently failing because the `inverse friction` written to the configuration file has no units. See [this](https://github.com/OpenBioSim/sire/issues/48) Sire issue thread for a discussion.

**Comment by lohedges** [comment]
Okay, this is due to some long-ago edits to the SOMD tests (not by me) that mean that the test function was returned _prior_ to the assertions being made, so they _always_ passed!

**Comment by chryswoods** [comment]
🤦
