### ISSUE TITLE
[BUG] process.getRecords not getting the same number of values for different columns

### ISSUE THREAD

**Issue by xiki-tempula** [OpenBioSim/biosimspace#52]
**Describe the bug**
When I run `energy_dict = process.getRecords()`, I expect that for every key, there should be the same number of values.

**To Reproduce**
```
mol_1 = BSS.Parameters.openff_unconstrained_2_0_0("C").getMolecule()
mol_2 = BSS.Parameters.openff_unconstrained_2_0_0("CO").getMolecule()
merged = BSS.Align.merge(mol_1, mol_2)
solvated = BSS.Solvent.tip3p(merged, box=3 * [4 * BSS.Units.Length.nanometer])
protocol = BSS.Protocol.FreeEnergyMinimisation()
process = BSS.Process.Amber(solvated, protocol, exe=amber_gpu)
protocol.start()
process.wait()
new = process.getSystem()
protocol = BSS.Protocol.FreeEnergyEquilibration()
process = BSS.Process.Amber(new, protocol, exe=amber_gpu)
process.start()
process.wait()
energy_dict = process.getRecords()
for key in energy_dict:
    print(len(energy_dict[key]))
```
Gives 
```
1002
1002
1503
1002
1503
1503
1503
1503
1503
1503
1002
1002
1002
1002
1002
1002
1002
501
501
501
501
501
501
501
1002
501
```

**Expected behavior**
The number of values one get from each key should be the same.

**Comment by lohedges** [comment]
Could you possibly uploaded the `stdout_file` used by this process, so that I don't have to re-run the simulation, which I can't do locally. Alternatively, just call `process.getOutput()` to get after the process finishes to get a zip file with the output, which you can upload. I'm assuming that the output formatting is different for a free energy simulation, so the logic used for the parsing isn't working correctly.

**Comment by xiki-tempula** [comment]
[amber_output.zip](https://github.com/OpenBioSim/biosimspace/files/11322246/amber_output.zip)

**Comment by xiki-tempula** [comment]
I think there will always be two TI regions for free energy claculations.

**Comment by xiki-tempula** [comment]
i think you might want this parameter at the getRecord level

**Comment by lohedges** [comment]
Thanks. I think I'll add some special handling for free energy protocols where I store two dictionaries, one for each TI region. If needed, I would also need to parse and store the information for the soft-core part and add methods to get back the records, since none currently exist.

**Comment by lohedges** [comment]
I think I now have this working locally. Could you possibly share output for a `FreeEnergyMinimisation` protocol? The AMBER output formatting is different for the regular `Minimisation` protocol and I have special handling to parse the records. I want to make sure that it still works for `FreeEnergyMinimisation`, and modify things if necessary.

**Comment by xiki-tempula** [comment]
[em.zip](https://github.com/OpenBioSim/biosimspace/files/11331293/em.zip)
