### ISSUE TITLE
[BUG] steered MD broken for AMBER

### ISSUE THREAD

**Issue by AdeleHardie** [OpenBioSim/biosimspace#61]
Please change line 257 of [_amber.py](../tree/devel/python/BioSimSpace/Process/_amber.py) to:
```python
            extra_options["plumedfile"] = "'plumed.dat'"
```
(i.e. add additional single quotes around `'plumed.dat'`).

The `amber.cfg` file should have:
```
  plumedfile='plumed.dat',
```
the single quotes are required. They must have been lost in changes made to the process code!

**Comment by lohedges** [comment]
Thanks for catching. I'll be able to add this when I'm back later in the week. This was introduced when adding a separate configuration file generation sub-package. This was based on code from the Exscientia Sandpit, where the error is present too.
