### ISSUE TITLE
Ambertools not found by BioSimSpace in jupyterlab

### ISSUE THREAD

**Issue by kexul** [OpenBioSim/biosimspace#7]
I just tried https://try.openbiosim.org/ with the quick start guide here: https://biosimspace.openbiosim.org/quickstart/index.html . 
An error occurred: 
![image](https://user-images.githubusercontent.com/5920217/219356531-9fb4f2fa-43de-404f-812f-694a2bdf05f8.png)

`!mamba install ambertools -c conda-forge`  says ambertools has already been installed. 
I tried `os.environ['AMBERHOME'] = /opt/conda`, but it doesn't help either.

**Comment by chryswoods** [comment]
Interesting... I've just tried and I get the same result. But - if I run this via `ipython` in the Jupyter lab Terminal, then everything works. The `AMBERHOME` environment variable is correctly set. But, it isn't set in the notebook.

Somehow, `AMBERHOME` is set in a shell in the Terminal, but not in the notebook.

Looking into this, I see that Jupyter now doesn't spawn a shell for the notebook, and so ignores the environment variables set in the bashrc file. The way to initialise variables is to put them into a startup script in `$HOME/.ipython/profile_default/startup/00-env.py`, e.g.

```
import os

os.environ["AMBERHOME"] = "/opt/conda"
```

I've done this for a temporary session, and it work. I will now update the notebook container image to do this generally. Everything should be ready in about 10-20 minutes (or so).

**Comment by lohedges** [comment]
Ah, interesting. This might explain some of the issues that I was seeing with GROMACS/PLUMED too, i.e. it worked on the command-line but not in the notebook. (The first time I tried it anyway.)

**Comment by chryswoods** [comment]
All fixed now. I ended up putting the environment variables into the docker image. I also added `PLUMED_ROOT` which I had missed before. I think everything should be working now (I've just tested myself, and it is good :-))
