### ISSUE TITLE
[BUG] Sire file caching breaking process.getSystem() when used interactively

### ISSUE THREAD

**Issue by lohedges** [OpenBioSim/biosimspace#92]
I _think_ that this might be fixed with the latest Sire trajectory code, but for certain binary formats, e.g. AMBER rst files, the Sire file cache means that a cached file will be re-used on read if the file name matches. This breaks the `process.getSystem()` functionality for BioSimSpace when used interactively, since you will keep getting back the same set of coordinates that were returned by the _initial_ call to the method.

As a simple example:

```python
In [1]: import BioSimSpace as BSS

In [2]: s0 = BSS.IO.readMolecules(["test0.rst", "test.top"])

In [3]: s1 = BSS.IO.readMolecules(["test1.rst", "test.top"])

In [4]: cp test1.rst test0.rst

In [5]: s2 = BSS.IO.readMolecules(["test0.rst", "test.top"])

In [6]: s0[0].coordinates()
Out[6]:
[(13.6813 A, 13.1482 A, 15.2733 A),
 (13.6813 A, 14.2382 A, 15.2733 A),
 (13.1676 A, 14.6020 A, 16.1632 A),
 (13.1676 A, 14.6020 A, 14.3835 A),
 (15.1088 A, 14.7890 A, 15.2733 A),
 (16.0719 A, 14.0256 A, 15.2733 A),
 (15.2367 A, 16.1178 A, 15.2733 A),
 (14.4145 A, 16.7043 A, 15.2733 A),
 (16.5346 A, 16.7621 A, 15.2733 A),
 (17.0889 A, 16.4637 A, 16.1632 A),
 (17.3426 A, 16.3690 A, 14.0412 A),
 (16.8046 A, 16.6695 A, 13.1421 A),
 (18.3118 A, 16.8671 A, 14.0676 A),
 (17.4899 A, 15.2890 A, 14.0320 A),
 (16.3940 A, 18.2776 A, 15.2733 A),
 (15.2820 A, 18.8009 A, 15.2734 A),
 (17.5274 A, 18.9831 A, 15.2734 A),
 (18.4183 A, 18.5073 A, 15.2733 A),
 (17.5274 A, 20.4321 A, 15.2734 A),
 (16.4999 A, 20.7959 A, 15.2734 A),
 (18.0411 A, 20.7959 A, 16.1632 A),
 (18.0411 A, 20.7959 A, 14.3835 A)]

In [7]: s1[0].coordinates()
Out[7]:
[(13.5716 A, 13.2645 A, 15.6562 A),
 (13.5789 A, 14.3357 A, 15.4607 A),
 (12.9188 A, 14.8503 A, 16.1556 A),
 (13.2508 A, 14.5096 A, 14.4374 A),
 (14.9839 A, 14.8623 A, 15.6344 A),
 (15.8174 A, 14.1710 A, 16.2109 A),
 (15.2255 A, 16.0742 A, 15.1400 A),
 (14.4553 A, 16.5900 A, 14.7412 A),
 (16.5121 A, 16.7744 A, 15.1675 A),
 (17.0302 A, 16.5318 A, 16.0974 A),
 (17.3649 A, 16.2773 A, 13.9880 A),
 (16.8675 A, 16.5102 A, 13.0454 A),
 (18.3440 A, 16.7586 A, 14.0058 A),
 (17.5069 A, 15.1985 A, 14.0639 A),
 (16.3136 A, 18.3070 A, 15.1113 A),
 (15.2321 A, 18.7896 A, 14.7589 A),
 (17.3760 A, 19.0610 A, 15.4345 A),
 (18.2254 A, 18.5853 A, 15.7018 A),
 (17.4120 A, 20.5239 A, 15.4079 A),
 (16.4059 A, 20.9376 A, 15.5047 A),
 (18.0217 A, 20.8950 A, 16.2344 A),
 (17.8478 A, 20.8669 A, 14.4677 A)]

In [8]: s2[0].coordinates()
Out[8]:
[(13.6813 A, 13.1482 A, 15.2733 A),
 (13.6813 A, 14.2382 A, 15.2733 A),
 (13.1676 A, 14.6020 A, 16.1632 A),
 (13.1676 A, 14.6020 A, 14.3835 A),
 (15.1088 A, 14.7890 A, 15.2733 A),
 (16.0719 A, 14.0256 A, 15.2733 A),
 (15.2367 A, 16.1178 A, 15.2733 A),
 (14.4145 A, 16.7043 A, 15.2733 A),
 (16.5346 A, 16.7621 A, 15.2733 A),
 (17.0889 A, 16.4637 A, 16.1632 A),
 (17.3426 A, 16.3690 A, 14.0412 A),
 (16.8046 A, 16.6695 A, 13.1421 A),
 (18.3118 A, 16.8671 A, 14.0676 A),
 (17.4899 A, 15.2890 A, 14.0320 A),
 (16.3940 A, 18.2776 A, 15.2733 A),
 (15.2820 A, 18.8009 A, 15.2734 A),
 (17.5274 A, 18.9831 A, 15.2734 A),
 (18.4183 A, 18.5073 A, 15.2733 A),
 (17.5274 A, 20.4321 A, 15.2734 A),
 (16.4999 A, 20.7959 A, 15.2734 A),
 (18.0411 A, 20.7959 A, 16.1632 A),
 (18.0411 A, 20.7959 A, 14.3835 A)]
 ```
 
As you can see, the coordinates for `s0` and `s1` differ, but `s2` has the _same_ coordinates as `s0` when it should match `s1`. Files to reproduce are [here](https://github.com/OpenBioSim/biosimspace/files/11624450/file_cache_issue.tar.gz). I'm not sure what other formats this is also an issue for. I've tested some others, e.g. rst7, and it works as expected.

@chryswoods: Do you know if this is no-longer an issue? I thought the cache was cleared when all files were parsed, but maybe this isn't true for certain formats. The above caused me a bit of a headache debugging something since the coordinates from `getSystem()` mismatched those from last frame of the the trajectory file obtained with `getTrajectory()`. Maybe there's a simple way of clearing the cache, or disabling it when I know a user is working interactively.

**Comment by chryswoods** [comment]
This should not be an issue for the new Trajectory code. Trajectory frames are now read live from the file, caching individual frames only within a Trajectory object. Could you try this with the `feature_trajectory_save` branch just to make sure? The code is all complete now - I am finishing up the docs before submitting the PR.

**Comment by chryswoods** [comment]
One issue though is that this will now break `s0`, as now trajectory frames are streamed. Changing the original file may break `s0` when it tries to read the next frame.

**Comment by lohedges** [comment]
Okay, I'll compile your branch and see what happens. Here the binary rst file is a restart that is written periodically by AMBER. It only every contains a single frame, but the same file is overwritten each time. I'll need to make sure that this still works. The other option is to use the trajectory file instead, but (at present) this means going via MDAnalysis or mdtraj, which can end up changing the box angles (hmm, that sounds familiar...).

**Comment by chryswoods** [comment]
Going into more detail, the trajectory code assumes that the files don't change while the object holding the system (or molecules) that have been loaded from the file are still alive. Changing the file during a running process thus leads to undefined behaviour. It would be computationally expensive to check if a file has changed, so the recommendation is that you shouldn't. Is there a way for `process.getSystem()` to write to a new file name when it is run again? I think this is something we may need to look at during a call, as I think is something that is fundamental to the design of both codes, and could lead to subtle bugs.

**Comment by lohedges** [comment]
The file is written by AMBER, but I should be able to modify `process.getSystem()` so that it copies the file to a temporary file (with a random name) before reading. I'll give things a go when I get a chance and ping you tomorrow if things don't work as expected.

**Comment by lohedges** [comment]
I can confirm that this is fixed by the updates on the [feature_trajectory_save](https://github.com/OpenBioSim/sire/tree/feature_trajectory_save) branch of Sire. This issue can be closed as part of the PR for that work. I'm just updating the `BioSimSpace.Process.Amber.getSystem()` code so that the binary rst file is always copied before read. This fix can be submitted independently.
