### ISSUE TITLE
[BUG] Unable to save BSS mol as PDB

### ISSUE THREAD

**Issue by noahharrison64** [OpenBioSim/biosimspace#93]
**Describe the bug**

**To Reproduce**
Something like this to create PDB/TOP files:
```
a_sdf = 'ejm31.sdf'
mol = BSS.IO.readMolecules(a_sdf)[0]
mol = BSS.Parameters.gaff2(mol, charge_method="BCC").getMolecule()
out = BSS.IO.saveMolecules('/mnt/block-volume/notebooks/hybrid_gen_tests/', mol, ["PDB", "GroTop"])
```
> OSError: Failed to save system to format: 'PDB'

**Input files**
https://drive.google.com/file/d/1TQTtNXS081vviCqa8cwLjy3sX57UARSh/view?usp=sharing

**(please complete the following information):**
 - OS: Linus 22.04
 - Version of Python: 3.9
 - Version of BioSimSpace: '2023.2.2'
 - Yes i think this is the latest version

**Additional context**
I've also been having issues reading in previously generated GRO and TOP files.

**Comment by lohedges** [comment]
Are you sure you are using the most recent version of the code from `devel`, e.g. using the `dev` label on conda? Your example works fine for me here.

>  I've also been having issues reading in previously generated GRO and TOP files.

For this issue: We recently came across a problem where GROMACS has (siliently) changed how it parses input files. It now seems to split certain records on whitespace, where previously it looked for a fixed with block. This means that molecules / systems that have names with a space in them no longer work. Previously we used to use things like `BioSImSpace System`, but this is now updated to `BioSimSpace_System`. Can you check you files and update these if this is the case? The latest version of Sire will always make sure that no whitespace is written to file.

[Here](https://github.com/OpenBioSim/biosimspace/files/11624698/files.tar.gz) are the files that were generated if you want to take a look.

If your example still fails with the most recent version, could you add `BSS.setVerbose(True)` near the top of your script. This _should_ let you know why the PDB writing failed.

**Comment by noahharrison64** [comment]
Hi, thanks for the rapid reply as always.

RE issue 1) This was just me being dumb - I forgot to include a filename and only gave a filepath when doing the saveMolecules function. Using BSS.IO.saveMolecules('/mnt/block-volume/notebooks/hybrid_gen_tests/out' fixes the issue. 

The main issue is the second, which is why I was originally running these simple tests (and messing up the syntax in issue 1) and encountering both errors. This issue still persists, even when the molecule / system name has no whitespace. Running the readMolecules() function  with verbosity on shows the following Sire error:

`OSError: SireError::io_error: Cannot load the molecules: Could not find a matching atom record: AtomName('Cl'), 
AtomNum(11), ResName('MOL'), ResNum(1) (call sire.error.get_last_error_details() for more info)`

It looks to me like this issue is due to a mismatch between the atom names in the TOP file vs the PDB file. In the PDB the atoms are labelled 'CL' whereas in the TOP they are labelled 'Cl'

**Comment by lohedges** [comment]
Ah, okay, I'm glad the first issue was an easy fix :-)

Yes, it looks like it's the name mismatch that's causing the issue. If you save to Gro87 and GroTop format and re-read, then everything is okay. I'll check the Sire GROMACS parser as I thought the logic for matching atoms was more flexible that that, but I think GROMACS itself might enforce something similar on read anyway so it might be important to be self-consistent. It might be possible to check the names after converting to uppoer/lower case, but there still could be issues if PDB and GroTop have particular formatting restrictions for the names, e.g. if one allows more characters than the other. Is there a reason why you want to combine PDB and GroTop in this case? If you need a PDB too, you could always save to three formats.

**Comment by noahharrison64** [comment]
Ah okay interesting... I was looking into merging two molecules to create single topology files, in order to run non-EQ FEP. I've been using PMX atomMapping and ligandHybrid to achieve this before but have encountered a few issues when it comes to multiprocessing, and so wanted to see if BSS could save the day. 

My only concern about using the Gro87 format is that it's not supported by RDKit. In the module I've been working on there is interconversion of molecules through RDKit, which doesn't support .gro files. I'm now wondering whether it'd be possible to load coordinates from an SDF and then add topology information via the .top file? This would be a simple workaround if supported.

**Comment by lohedges** [comment]
I think we only support SDF format as a means to create a new system from scratch, rather than being used to add additional information to an existing system. That said, it should be possible to create two systems then copy the coordinates from one to the other.

**Comment by chryswoods** [comment]
Yes, @lohedges is right. Both SDF and GroTop are what we call "topology" parsers, i.e. they can both create topologies, and so both can't be loaded together into the same system. We can only combine one "topology" parser with any number of what we call "frame" parsers (files that only contain coordinate, velocity or force data). Some parsers are both "topology" and "frame", so can fall back to being frames if there is already a leading "topology" parser. However, our SDF parser doesn't have that capability. It can only be a "topology", and so can't be used with a GroTop (also a "topology").

@lohedges is right - the easiest way to do this will be to load both files as different systems, and then copy the coordinates from one to the other.

**Comment by chryswoods** [comment]
(also, you can save to other file formats if you want, including to SDF or any other file format that rdkit supports. Use `sire.save(mols, "output", format=[list_of_formats])` to save the file to what you want. There is no requirement to have consistent formats, i.e. you can save to GroTop and PDB, or GroTop and SDF instead, and are not restricted to GroTop and Gro87)

**Comment by lohedges** [comment]
I also completely forgot to mention that Sire now has inbuilt functionality to convert directly to/from RDKit molecule objects. This is wrapped in BioSimSpace via the `BioSimSpace.Convert` sub-package. Documentation is [here](https://biosimspace.openbiosim.org/api/index_Convert.html). This would completely eliminate the need to go via intermediate files.

**Comment by noahharrison64** [comment]
Thanks to both of you for all the info @chryswoods @lohedges. Native conversion capabilities will be very useful!
